name: Build UmaAiForm Only

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up MSBuild
        uses: microsoft/setup-msbuild@v1.3.1

      - name: Build UmaAiForm
        run: msbuild UmaAiForm/UmaAiForm.csproj /p:Configuration=Release

      - name: Upload Release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            **/bin/Release/UmaAiForm.exe
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}